### ISSUE TITLE
Call to undefined method stdClass::close() 

### ISSUE THREAD

**Issue by fising** [open-smf/connection-pool#1]
> [2019-05-27 22:06:12 *28.7]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Error: Call to undefined method stdClass::close() in /app/vendor/open-smf/connection-pool/src/Connectors/PhpRedisConnector.php:32
Stack trace:
#0 /app/vendor/open-smf/connection-pool/src/ConnectionPool.php(206): Smf\ConnectionPool\Connectors\PhpRedisConnector->disconnect(Object(stdClass))
#1 {main}
  thrown in /app/vendor/open-smf/connection-pool/src/Connectors/PhpRedisConnector.php on line 32.

**Comment by hhxsv5** [comment]
应该是你的phpredis扩展版本低了，需要[PhpRedis >= 4.2.0](https://github.com/phpredis/phpredis#close)。

**Comment by fising** [comment]
好的，我尝试升级看看。

**Comment by fising** [comment]
> 应该是你的phpredis扩展版本低了，需要[PhpRedis >= 4.2.0](https://github.com/phpredis/phpredis#close)。

我看了一下，我的 Redis 扩展版本是 4.2.0:

>redis
Redis Support => enabled
Redis Version => 4.2.0
Available serializers => php

Swoole 版本是 4.2.10

**Comment by hhxsv5** [comment]
跟 Swoole 没关系，我用的 PhpRedis 4.3.0，你升级到这个版本试试。不过也很奇怪，[4.2.0](https://github.com/phpredis/phpredis/blob/4.2.0/php_redis.h)是有这个函数的，你没重启？
看看`php --rc Redis|grep close`
root@14197b8b2f0d:/docker# php --rc Redis|grep close
    Method [ <internal:redis> public method close ] {

**Comment by fising** [comment]
> $php --rc Redis|grep close
   Method [ <internal:redis> public method close ] {

**Comment by fising** [comment]
关键问题应该是Redis实例变成了stdClass吧？

**Comment by hhxsv5** [comment]
你`return`连接时是不是搞错对象了？

**Comment by fising** [comment]
> 你`return`连接时是不是搞错对象了？

我也怀疑这个问题，还在检查。

**Comment by hhxsv5** [comment]
[v1.0.10](https://github.com/open-smf/connection-pool/releases/tag/v1.0.10)
