### ISSUE TITLE
如何在 swoole 的自定义进程里使用连接池

### ISSUE THREAD

**Issue by OverNaive** [open-smf/connection-pool#10]
目前看例子里的 `Usage in Swoole Server` 中，是通过绑定事件

```
        $this->swoole->on('WorkerStart', $createPools);
        $this->swoole->on('WorkerStop', $closePools);
        $this->swoole->on('WorkerError', $closePools);
```

似乎自定义进程没有对应的事件。

通过 [addProcess()](https://wiki.swoole.com/#/server/methods?id=addprocess) 方法启动的自定义进程（常驻），如何使用连接池呢？

感谢

**Comment by hhxsv5** [comment]
按普通示例操作即可，[coroutine-runtime-pdo](https://github.com/open-smf/connection-pool/blob/master/examples/coroutine-runtime-pdo.php)。

**Comment by OverNaive** [comment]
谢谢
