### ISSUE TITLE
php 8.2 Error

### ISSUE THREAD

**Issue by YvesHo0968** [open-smf/connection-pool#17]
#0 [8192]ErrorException in ConnectionPool.php line 264
Creation of dynamic property think\cache\driver\Redis::$__lat is deprecated
                }
            }
        });
    }

    protected function createConnection()
    {
        $this->connectionCount++;
        $connection = $this->connector->connect($this->connectionConfig);
        $connection->{static::KEY_LAST_ACTIVE_TIME} = time();
        return $connection;
    }

    protected function removeConnection($connection)
    {
        $this->connectionCount--;
        Coroutine::create(function () use ($connection) {
            try {
                $this->connector->disconnect($connection);

PHP 8.2弃用了动态声明的类属性

**Comment by hhxsv5** [comment]
composer require "open-smf/connection-pool:~2.0"
