### ISSUE TITLE
在运行的过程中有时候会报如下错误

### ISSUE THREAD

**Issue by niceguy-php** [open-smf/connection-pool#4]
在运行的过程中有时候会报错
PHP Fatal error:  Swoole\Coroutine\Redis::__construct(): constructor can only be called once in /xxxx/swoole_api/vendor/open-smf/connection-pool/src/Connectors/CoroutineRedisConnector.php on line 11

**Comment by niceguy-php** [comment]
原程序代码
$config = $this->configs[$name];
        $config['options'] = [
            'connect_timeout' => 1,
            'timeout'         => 5,
        ];

        $pool = new ConnectionPool(
            [
                'minActive'         => self::DEFAULT_MIN_ACTIVE,
                'maxActive'         => self::DEFAULT_MAX_ACTIVE,
                'maxWaitTime'       => self::DEFAULT_MAX_WAIT_TIME,
                'maxIdleTime'       => self::DEFAULT_MAX_IDLE_TIME,
                'idleCheckInterval' => self::DEFAULT_IDLE_CHECK_INTERVAL,
            ],
            new CoroutineRedisConnector(),
            $config
        );
        echo "Initializing connection pool\n";
        $pool->init();
        $this->addConnectionPool($name, $pool);

**Comment by hhxsv5** [comment]
Swoole 什么版本？

**Comment by niceguy-php** [comment]
> Swoole 什么版本？

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 4.3.6
Built => Jul 18 2019 18:25:01
coroutine => enabled
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
http2 => enabled
pcre => enabled
zlib => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608

**Comment by hhxsv5** [comment]
尝试升级Swoole解决。
